# Generated by Django 5.2.11 on 2026-04-08 23:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=220, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                ("goal_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "current_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("currency", models.CharField(default="GHS", max_length=3)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("image_url", models.URLField(blank=True, default="")),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="campaigns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "campaigns",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Donation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="GHS", max_length=3)),
                ("phone_number", models.CharField(max_length=20)),
                ("donor_name", models.CharField(max_length=100)),
                ("channel", models.CharField(max_length=20)),
                (
                    "hubtel_reference",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                (
                    "hubtel_session_id",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "hubtel_order_id",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("once", "One-time"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("annually", "Annually"),
                        ],
                        default="once",
                        max_length=20,
                    ),
                ),
                ("is_anonymous", models.BooleanField(default=False)),
                ("message", models.TextField(blank=True, default="")),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="donations",
                        to="donations.campaign",
                    ),
                ),
                (
                    "donor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="donations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "donations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RecurringDonation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "hubtel_recurring_invoice_id",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("annually", "Annually"),
                        ],
                        max_length=20,
                    ),
                ),
                ("next_payment_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("failure_count", models.IntegerField(default=0)),
                (
                    "donation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recurring",
                        to="donations.donation",
                    ),
                ),
            ],
            options={
                "db_table": "recurring_donations",
            },
        ),
        migrations.AddIndex(
            model_name="campaign",
            index=models.Index(
                fields=["is_active", "status"], name="campaigns_is_acti_ea757f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="donation",
            index=models.Index(
                fields=["campaign", "status"], name="donations_campaig_59c31d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="donation",
            index=models.Index(fields=["donor"], name="donations_donor_i_e43edd_idx"),
        ),
        migrations.AddIndex(
            model_name="donation",
            index=models.Index(fields=["status"], name="donations_status_14f677_idx"),
        ),
    ]
