# Generated by Django 5.2.11 on 2026-04-09 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0001_initial_donation_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donation",
            name="channel",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
