# Generated by Django 5.2.11 on 2026-03-04 09:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("nests", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Badge",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("icon", models.URLField(blank=True, max_length=500)),
                (
                    "criteria_type",
                    models.CharField(
                        choices=[
                            ("points_threshold", "Points Threshold"),
                            ("courses_completed", "Courses Completed"),
                            ("streak_days", "Streak Days"),
                            ("assignments_submitted", "Assignments Submitted"),
                        ],
                        max_length=25,
                    ),
                ),
                (
                    "criteria_value",
                    models.PositiveIntegerField(
                        help_text="Numeric threshold for earning this badge."
                    ),
                ),
            ],
            options={
                "db_table": "badges",
                "ordering": ["criteria_value"],
            },
        ),
        migrations.CreateModel(
            name="PointConfiguration",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("video_complete", "Video Completed"),
                            ("document_read", "Document Read"),
                            ("assignment_submit", "Assignment Submitted"),
                            ("assignment_graded", "Assignment Graded"),
                            ("module_complete", "Module Completed"),
                            ("check_in", "Daily Check-In"),
                            ("post_created", "Post Created"),
                            ("resource_shared", "Resource Shared"),
                            ("event_attended", "Event Attended"),
                        ],
                        max_length=30,
                        unique=True,
                    ),
                ),
                ("points_value", models.PositiveIntegerField(default=10)),
                ("is_active", models.BooleanField(default=True)),
                ("description", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "db_table": "point_configurations",
                "ordering": ["activity_type"],
            },
        ),
        migrations.CreateModel(
            name="PointTransaction",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "points",
                    models.IntegerField(
                        help_text="Positive for earn, negative for spend."
                    ),
                ),
                ("activity_type", models.CharField(max_length=30)),
                (
                    "source",
                    models.CharField(
                        choices=[("auto", "Automatic"), ("manual", "Manual Award")],
                        default="auto",
                        max_length=10,
                    ),
                ),
                (
                    "source_id",
                    models.UUIDField(
                        blank=True,
                        help_text="ID of the entity that triggered this (content item, etc.)",
                        null=True,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=250)),
                (
                    "awarded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="points_awarded",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "nest",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="point_transactions",
                        to="nests.nest",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="point_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "point_transactions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="point_trans_user_id_62267a_idx",
                    ),
                    models.Index(
                        fields=["user", "activity_type"],
                        name="point_trans_user_id_cf2225_idx",
                    ),
                    models.Index(
                        fields=["nest", "user"], name="point_trans_nest_id_e6bd2d_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserBadge",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("earned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "badge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="earners",
                        to="points.badge",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="badges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_badges",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "badge"), name="unique_user_badge"
                    )
                ],
            },
        ),
    ]
