# Generated by Django 5.2.11 on 2026-03-09 16:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nests", "0002_nestevent_nest_events_nest_id_e47a9c_idx_and_more"),
        ("points", "0002_seed_point_configs"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="pointtransaction",
            index=models.Index(
                fields=["activity_type", "created_at"],
                name="point_trans_activit_95391a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pointtransaction",
            index=models.Index(
                fields=["-created_at"], name="point_trans_created_b9d3b4_idx"
            ),
        ),
    ]
