# Generated by Django 5.2.11 on 2026-03-16 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("points", "0003_pointtransaction_point_trans_activit_95391a_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="badge",
            name="slug",
            field=models.SlugField(blank=True, default="", max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name="badge",
            name="criteria_type",
            field=models.CharField(
                choices=[
                    ("points_threshold", "Points Threshold"),
                    ("courses_completed", "Courses Completed"),
                    ("streak_days", "Streak Days"),
                    ("assignments_submitted", "Assignments Submitted"),
                    ("community_contributions", "Community Contributions"),
                    ("quizzes_passed", "Quizzes Passed"),
                    ("events_attended", "Events Attended"),
                    ("nests_joined", "Nests Joined"),
                    ("one_time_event", "One-Time Event"),
                    ("competitive", "Competitive"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="badge",
            name="icon",
            field=models.URLField(blank=True, max_length=2000),
        ),
    ]
