# Generated by Django 5.2.11 on 2026-03-16 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("points", "0004_badge_slug_criteria_types"),
    ]

    operations = [
        migrations.AlterField(
            model_name="badge",
            name="icon",
            field=models.TextField(blank=True),
        ),
    ]
