# Generated by Django 5.2.15 on 2026-07-28 23:00

import uuid
from django.conf import settings
from django.db import migrations, models


def seed_policy(apps, schema_editor):
    """Create the singleton policy row so the award path never sees an empty table.

    Defaults (25 per award / 250 per mentor per day) are deliberately far tighter
    than the previous hardcoded 1000-per-click-with-no-daily-limit behaviour.
    """
    PointsPolicy = apps.get_model("points", "PointsPolicy")
    if not PointsPolicy.objects.exists():
        PointsPolicy.objects.create(
            max_manual_award=25,
            daily_points_per_mentor=250,
            is_enforced=True,
        )


def unseed_policy(apps, schema_editor):
    apps.get_model("points", "PointsPolicy").objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("nests", "0012_nest_category_nestactivity"),
        ("points", "0008_remove_resource_eagle_badge"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PointsPolicy",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "max_manual_award",
                    models.PositiveIntegerField(
                        default=25,
                        help_text="Maximum points a mentor may award in a single transaction.",
                    ),
                ),
                (
                    "daily_points_per_mentor",
                    models.PositiveIntegerField(
                        default=250,
                        help_text="Maximum total points a mentor may award per day (UTC).",
                    ),
                ),
                (
                    "is_enforced",
                    models.BooleanField(
                        default=True,
                        help_text="Escape hatch — uncheck to suspend limits during an incident.",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Points policies",
                "db_table": "points_policy",
            },
        ),
        migrations.AddIndex(
            model_name="pointtransaction",
            index=models.Index(
                fields=["awarded_by", "-created_at"],
                name="point_trans_awarded_22d8cb_idx",
            ),
        ),
        migrations.RunPython(seed_policy, unseed_policy),
    ]
