# Generated by Django 5.2.11 on 2026-03-04 09:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("nests", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentModule",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_published", models.BooleanField(default=False)),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        default="beginner",
                        max_length=15,
                    ),
                ),
                (
                    "points_value",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Bonus points awarded on module completion.",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        limit_choices_to={"role": "eagle"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_modules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "nest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modules",
                        to="nests.nest",
                    ),
                ),
            ],
            options={
                "db_table": "content_modules",
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContentItem",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("video", "Video"),
                            ("document", "Document"),
                            ("reading", "Reading"),
                            ("quiz", "Quiz"),
                        ],
                        default="reading",
                        max_length=15,
                    ),
                ),
                ("file_url", models.URLField(blank=True, max_length=500)),
                ("thumbnail_url", models.URLField(blank=True, max_length=500)),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        default=0, help_text="Duration in minutes (for videos)."
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        default=0, help_text="File size in bytes."
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "points_value",
                    models.PositiveIntegerField(
                        default=0, help_text="Points earned on completing this item."
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(
                        default=True, help_text="Required for module completion."
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="content.contentmodule",
                    ),
                ),
            ],
            options={
                "db_table": "content_items",
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="Assignment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("due_date", models.DateTimeField(blank=True, null=True)),
                ("points_value", models.PositiveIntegerField(default=0)),
                ("max_submissions", models.PositiveIntegerField(default=1)),
                (
                    "allowed_file_types",
                    models.JSONField(
                        default=list, help_text='E.g. ["pdf", "docx", "pptx"]'
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="content.contentmodule",
                    ),
                ),
            ],
            options={
                "db_table": "assignments",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContentProgress",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                        ],
                        default="not_started",
                        max_length=15,
                    ),
                ),
                ("progress_percentage", models.FloatField(default=0.0)),
                (
                    "watch_duration_seconds",
                    models.PositiveIntegerField(
                        default=0, help_text="Video watch time in seconds."
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("last_accessed_at", models.DateTimeField(auto_now=True)),
                (
                    "content_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_records",
                        to="content.contentitem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "content_progress",
            },
        ),
        migrations.CreateModel(
            name="AssignmentSubmission",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("file_url", models.URLField(max_length=500)),
                ("notes", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("graded", "Graded"),
                            ("returned", "Returned for Revision"),
                        ],
                        default="submitted",
                        max_length=15,
                    ),
                ),
                ("grade", models.CharField(blank=True, max_length=20)),
                ("feedback", models.TextField(blank=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="content.assignment",
                    ),
                ),
                (
                    "graded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="graded_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignment_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "assignment_submissions",
                "ordering": ["-submitted_at"],
                "indexes": [
                    models.Index(
                        fields=["assignment", "user"],
                        name="assignment__assignm_d41b5d_idx",
                    ),
                    models.Index(
                        fields=["user", "status"], name="assignment__user_id_c7ae58_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="contentmodule",
            index=models.Index(
                fields=["nest", "is_published"], name="content_mod_nest_id_655bf0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contentmodule",
            index=models.Index(
                fields=["created_by"], name="content_mod_created_b90d0f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contentitem",
            index=models.Index(
                fields=["module", "order"], name="content_ite_module__a3346e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contentprogress",
            index=models.Index(
                fields=["user", "status"], name="content_pro_user_id_03369c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contentprogress",
            index=models.Index(
                fields=["content_item"], name="content_pro_content_0daf47_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="contentprogress",
            constraint=models.UniqueConstraint(
                fields=("user", "content_item"), name="unique_user_content_progress"
            ),
        ),
    ]
