# Generated by Django 5.2.11 on 2026-03-05 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
        ("nests", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentmodule",
            name="created_by",
            field=models.ForeignKey(
                limit_choices_to=models.Q(
                    ("role", "eagle"), ("role", "admin"), _connector="OR"
                ),
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_modules",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="contentmodule",
            name="nest",
            field=models.ForeignKey(
                blank=True,
                help_text="If null, this is a global module visible to everyone.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="modules",
                to="nests.nest",
            ),
        ),
    ]
