# Generated by Django 5.2.11 on 2026-03-09 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_alter_contentmodule_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentmodule",
            name="module_type",
            field=models.CharField(
                choices=[("assignment", "Assignment"), ("resource", "Resource")],
                default="assignment",
                max_length=15,
            ),
        ),
    ]
