# Generated by Django 5.2.11 on 2026-03-10 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_contentmodule_module_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentmodule',
            name='thumbnail_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
