# Generated by Django 5.2.11 on 2026-03-24 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0011_add_assignment_performance_indexes"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="assignment",
            new_name="assignments_nest_id_4cb69e_idx",
            old_name="assignment_nest_type_idx",
        ),
        migrations.RenameIndex(
            model_name="assignment",
            new_name="assignments_nest_id_af0fba_idx",
            old_name="assignment_nest_creator_idx",
        ),
    ]
