# Generated by Django 5.2.11 on 2026-03-04 09:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Nest",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("slug", models.SlugField(max_length=170, unique=True)),
                ("description", models.TextField(blank=True)),
                ("industry_focus", models.CharField(blank=True, max_length=100)),
                ("banner_image", models.URLField(blank=True, max_length=500)),
                (
                    "privacy",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("invitation_only", "Invitation Only"),
                        ],
                        default="public",
                        max_length=20,
                    ),
                ),
                ("allow_referrals", models.BooleanField(default=True)),
                ("meeting_link", models.URLField(blank=True, max_length=500)),
                ("max_members", models.PositiveIntegerField(default=50)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "eagle",
                    models.ForeignKey(
                        limit_choices_to={"role": "eagle"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_nests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "nests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MentorshipRequest",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True, help_text="Introduction message from the Eaglet."
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "eaglet",
                    models.ForeignKey(
                        limit_choices_to={"role": "eaglet"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mentorship_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "nest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requests",
                        to="nests.nest",
                    ),
                ),
            ],
            options={
                "db_table": "mentorship_requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NestEvent",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("event_date", models.DateTimeField()),
                ("meeting_link", models.URLField(blank=True, max_length=500)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("workshop", "Workshop"),
                            ("session", "Session"),
                            ("meeting", "Meeting"),
                        ],
                        default="session",
                        max_length=15,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "nest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="nests.nest",
                    ),
                ),
            ],
            options={
                "db_table": "nest_events",
                "ordering": ["event_date"],
            },
        ),
        migrations.CreateModel(
            name="NestMembership",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("member", "Member"), ("eagle_scout", "Eagle Scout")],
                        default="member",
                        max_length=15,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("removed", "Removed"),
                        ],
                        default="active",
                        max_length=10,
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("progress_percentage", models.FloatField(default=0.0)),
                (
                    "nest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="nests.nest",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nest_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "nest_memberships",
            },
        ),
        migrations.CreateModel(
            name="NestPost",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "post_type",
                    models.CharField(
                        choices=[("post", "Post"), ("announcement", "Announcement")],
                        default="post",
                        max_length=15,
                    ),
                ),
                ("content", models.TextField()),
                ("attachment_url", models.URLField(blank=True, max_length=500)),
                ("attachment_type", models.CharField(blank=True, max_length=10)),
                ("likes_count", models.PositiveIntegerField(default=0)),
                ("comments_count", models.PositiveIntegerField(default=0)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nest_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "nest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="nests.nest",
                    ),
                ),
            ],
            options={
                "db_table": "nest_posts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NestPostComment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.TextField()),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nest_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="nests.nestpost",
                    ),
                ),
            ],
            options={
                "db_table": "nest_post_comments",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="NestResource",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("file_url", models.URLField(max_length=500)),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("pptx", "PowerPoint"),
                            ("link", "External Link"),
                            ("video", "Video"),
                            ("document", "Document"),
                        ],
                        default="document",
                        max_length=15,
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(default=0, help_text="Size in bytes"),
                ),
                (
                    "nest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resources",
                        to="nests.nest",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_resources",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "nest_resources",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="nest",
            index=models.Index(fields=["eagle"], name="nests_eagle_i_4fec6f_idx"),
        ),
        migrations.AddIndex(
            model_name="nest",
            index=models.Index(fields=["privacy"], name="nests_privacy_1d46d3_idx"),
        ),
        migrations.AddIndex(
            model_name="nest",
            index=models.Index(fields=["is_active"], name="nests_is_acti_2adf37_idx"),
        ),
        migrations.AddIndex(
            model_name="mentorshiprequest",
            index=models.Index(
                fields=["nest", "status"], name="mentorship__nest_id_4764a4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mentorshiprequest",
            index=models.Index(
                fields=["eaglet", "status"], name="mentorship__eaglet__848e6d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="nestmembership",
            index=models.Index(
                fields=["nest", "status"], name="nest_member_nest_id_e51f67_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="nestmembership",
            index=models.Index(
                fields=["user", "status"], name="nest_member_user_id_202c3f_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="nestmembership",
            constraint=models.UniqueConstraint(
                fields=("nest", "user"), name="unique_nest_membership"
            ),
        ),
        migrations.AddIndex(
            model_name="nestpost",
            index=models.Index(
                fields=["nest", "-created_at"], name="nest_posts_nest_id_9df701_idx"
            ),
        ),
    ]
