# Generated by Django 5.2.11 on 2026-03-09 16:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nests", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="nestevent",
            index=models.Index(
                fields=["nest", "event_date"], name="nest_events_nest_id_e47a9c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="nestevent",
            index=models.Index(
                fields=["event_date"], name="nest_events_event_d_a59b97_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="nestpost",
            index=models.Index(fields=["author"], name="nest_posts_author__a97184_idx"),
        ),
        migrations.AddIndex(
            model_name="nestpost",
            index=models.Index(
                fields=["-created_at"], name="nest_posts_created_4f3754_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="nestresource",
            index=models.Index(
                fields=["nest", "-created_at"], name="nest_resour_nest_id_9641ac_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="nestresource",
            index=models.Index(
                fields=["uploaded_by"], name="nest_resour_uploade_467795_idx"
            ),
        ),
    ]
