# Generated by Django 5.2.11 on 2026-03-14 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nests", "0003_add_event_attendance"),
    ]

    operations = [
        migrations.AddField(
            model_name="nestpostcomment",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="nests.nestpostcomment",
            ),
        ),
    ]
