# Generated by Django 5.2.11 on 2026-05-03 04:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nests", "0005_add_nestpostlike"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Program",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="programs_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "nest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="programs",
                        to="nests.nest",
                    ),
                ),
            ],
            options={
                "db_table": "nest_programs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProgramObjective",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="objectives",
                        to="nests.program",
                    ),
                ),
            ],
            options={
                "db_table": "nest_program_objectives",
                "ordering": ["program", "order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProgramObjectiveRule",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("modules_completed", "Modules completed"),
                            ("assignments_passed", "Assignments passed"),
                            ("points_earned", "Points earned"),
                            ("posts_count", "Community posts"),
                            ("streak_days", "Activity streak (days)"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "target",
                    models.PositiveIntegerField(
                        help_text="Numeric threshold the mentee must hit (e.g. 5 modules, 1000 points)."
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Rule-specific params (e.g. {'module_ids': [...]} for scoped rules).",
                    ),
                ),
                (
                    "objective",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rules",
                        to="nests.programobjective",
                    ),
                ),
            ],
            options={
                "db_table": "nest_program_objective_rules",
                "ordering": ["objective", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="program",
            index=models.Index(
                fields=["nest", "status"], name="nest_progra_nest_id_c23b40_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="program",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "active")),
                fields=("nest",),
                name="uniq_active_program_per_nest",
            ),
        ),
        migrations.AddIndex(
            model_name="programobjective",
            index=models.Index(
                fields=["program"], name="nest_progra_program_b49ca7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="programobjectiverule",
            index=models.Index(
                fields=["objective", "rule_type"], name="nest_progra_objecti_742c28_idx"
            ),
        ),
    ]
