# Generated by Django 5.2.11 on 2026-05-03 09:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nests", "0006_program_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgramEnrollment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("released", "Released"),
                            ("opted_out", "Opted out"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("application_message", models.TextField(blank=True)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("exit_reason", models.TextField(blank=True)),
                ("rules_snapshot", models.JSONField(blank=True, default=dict)),
                (
                    "ended_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="enrollments_ended",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "mentee",
                    models.ForeignKey(
                        limit_choices_to={"role": "eaglet"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="program_enrollments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enrollments",
                        to="nests.program",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="enrollments_reviewed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "nest_program_enrollments",
                "ordering": ["-requested_at"],
            },
        ),
        migrations.CreateModel(
            name="ProgramExitRequest",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reason", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("denied", "Denied"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("decision_note", models.TextField(blank=True)),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exit_requests_decided",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exit_requests",
                        to="nests.programenrollment",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exit_requests_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "nest_program_exit_requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="programenrollment",
            index=models.Index(
                fields=["mentee", "status"], name="nest_progra_mentee__80ea75_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="programenrollment",
            index=models.Index(
                fields=["program", "status"], name="nest_progra_program_9afc08_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="programenrollment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "pending")),
                fields=("mentee",),
                name="uniq_pending_enrollment_per_mentee",
            ),
        ),
        migrations.AddConstraint(
            model_name="programenrollment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "active")),
                fields=("mentee",),
                name="uniq_active_enrollment_per_mentee",
            ),
        ),
        migrations.AddConstraint(
            model_name="programexitrequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "pending")),
                fields=("enrollment",),
                name="uniq_pending_exit_per_enrollment",
            ),
        ),
    ]
