# Generated by Django 5.2.11 on 2026-05-03 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nests", "0008_data_backfill"),
    ]

    operations = [
        migrations.CreateModel(
            name="MenteeLevelConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("level", models.PositiveSmallIntegerField(unique=True)),
                ("name", models.CharField(max_length=64)),
                ("points_required", models.PositiveIntegerField()),
                ("unlocks_mentor_application", models.BooleanField(default=False)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "db_table": "mentee_level_configs",
                "ordering": ["level"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("level__gte", 1), ("level__lte", 5)),
                        name="mentee_level_in_range_1_5",
                    )
                ],
            },
        ),
    ]
