# Generated by Django 5.2.15 on 2026-07-20 16:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nests", "0011_raise_mentee_level_thresholds"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="nest",
            name="category",
            field=models.CharField(
                choices=[
                    ("faith", "Faith & Profession"),
                    ("leadership", "Leadership"),
                    ("finance", "Finance & Stewardship"),
                    ("relationships", "Relationships"),
                    ("career", "Career"),
                    ("other", "Other"),
                ],
                db_index=True,
                default="other",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="NestActivity",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("member_joined", "Member joined"),
                            ("member_left", "Member left"),
                            ("member_removed", "Member removed"),
                            ("content_shared", "Content shared"),
                            ("post_created", "Post created"),
                            ("nest_created", "Nest created"),
                            ("nest_archived", "Nest archived"),
                            ("mentor_action", "Mentor action"),
                        ],
                        max_length=20,
                    ),
                ),
                ("target", models.CharField(blank=True, max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="nest_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "nest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="nests.nest",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Nest activities",
                "db_table": "nest_activities",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["nest", "-created_at"],
                        name="nest_activi_nest_id_747090_idx",
                    ),
                    models.Index(
                        fields=["action_type"], name="nest_activi_action__e0de00_idx"
                    ),
                ],
            },
        ),
    ]
