# Generated by Django 5.2.11 on 2026-02-23 05:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorKYC',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('government_id', models.FileField(blank=True, help_text="Government-issued ID (passport, driver's license, national ID)", null=True, upload_to='kyc/government_ids/%Y/%m/')),
                ('government_id_type', models.CharField(blank=True, help_text='Type of government ID uploaded', max_length=50)),
                ('government_id_verified', models.BooleanField(default=False)),
                ('church_name', models.CharField(blank=True, help_text='Current church or ministry name', max_length=200)),
                ('church_role', models.CharField(blank=True, help_text='Role/position in the church', max_length=100)),
                ('years_of_service', models.PositiveIntegerField(blank=True, help_text='Years of active service in ministry', null=True)),
                ('spiritual_testimony', models.TextField(blank=True, help_text='Brief spiritual journey/testimony (max 500 words)', max_length=2500)),
                ('recommendation_letter', models.FileField(blank=True, help_text='Recommendation letter from pastor or ministry leader', null=True, upload_to='kyc/recommendations/%Y/%m/')),
                ('area_of_expertise', models.CharField(blank=True, help_text='Primary area of expertise for mentoring', max_length=100)),
                ('current_occupation', models.CharField(blank=True, help_text='Current occupation or profession', max_length=200)),
                ('linkedin_url', models.URLField(blank=True, help_text='LinkedIn profile URL')),
                ('mentorship_interests', models.JSONField(blank=True, default=list, help_text='Topics comfortable mentoring in (stored as JSON array)')),
                ('background_check_consent', models.BooleanField(default=False, help_text='Consent to background check')),
                ('code_of_conduct_agreed', models.BooleanField(default=False, help_text='Agreement to mentor code of conduct')),
                ('statement_of_faith_agreed', models.BooleanField(default=False, help_text='Agreement with statement of faith')),
                ('digital_signature', models.TextField(blank=True, help_text='Digital signature (typed name or base64 signature image)')),
                ('consent_date', models.DateTimeField(blank=True, help_text='Date when consent was given', null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('requires_changes', 'Requires Changes')], default='draft', max_length=20)),
                ('current_step', models.PositiveIntegerField(default=1, help_text='Current step in the KYC wizard (1-4)')),
                ('submitted_at', models.DateTimeField(blank=True, help_text='When the application was submitted', null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='When the application was reviewed', null=True)),
                ('review_notes', models.TextField(blank=True, help_text='Internal notes from the reviewer')),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection (shown to applicant)')),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Admin who reviewed the application', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_kyc_applications', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_kyc', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mentor KYC',
                'verbose_name_plural': 'Mentor KYC Applications',
                'db_table': 'mentor_kyc',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='mentor_kyc_status_a6ccfc_idx'), models.Index(fields=['submitted_at'], name='mentor_kyc_submitt_de33ad_idx')],
            },
        ),
    ]
