# Generated by Django 5.2.11 on 2026-02-23 06:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_mentor_kyc"),
    ]

    operations = [
        migrations.CreateModel(
            name="EagletProfile",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "age_group",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("13_17", "13-17 years"),
                            ("18_24", "18-24 years"),
                            ("25_34", "25-34 years"),
                            ("35_44", "35-44 years"),
                            ("45_plus", "45+ years"),
                        ],
                        help_text="Age group for appropriate mentor matching",
                        max_length=20,
                    ),
                ),
                (
                    "educational_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("high_school", "High School"),
                            ("undergraduate", "Undergraduate"),
                            ("graduate", "Graduate/Postgraduate"),
                            ("professional", "Working Professional"),
                            ("other", "Other"),
                        ],
                        help_text="Current educational level",
                        max_length=20,
                    ),
                ),
                (
                    "field_of_study",
                    models.CharField(
                        blank=True,
                        help_text="Field of study or profession",
                        max_length=200,
                    ),
                ),
                (
                    "institution",
                    models.CharField(
                        blank=True,
                        help_text="School, university, or workplace",
                        max_length=200,
                    ),
                ),
                (
                    "interests",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Areas of interest for mentorship (stored as JSON array)",
                    ),
                ),
                (
                    "goals",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Mentorship goals (stored as JSON array)",
                    ),
                ),
                (
                    "preferred_mentor_expertise",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Preferred mentor expertise areas (stored as JSON array)",
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True, help_text="Short bio about yourself", max_length=500
                    ),
                ),
                (
                    "expectations",
                    models.TextField(
                        blank=True,
                        help_text="What you hope to gain from mentorship",
                        max_length=1000,
                    ),
                ),
                (
                    "onboarding_completed",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the user has completed optional onboarding",
                    ),
                ),
                (
                    "onboarding_completed_at",
                    models.DateTimeField(
                        blank=True, help_text="When onboarding was completed", null=True
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eaglet_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Eaglet Profile",
                "verbose_name_plural": "Eaglet Profiles",
                "db_table": "eaglet_profiles",
                "ordering": ["-created_at"],
            },
        ),
    ]
