# Generated by Django 5.2.11 on 2026-02-23 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_eagletprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="google_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Google OAuth user ID",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_picture_url",
            field=models.URLField(
                blank=True,
                help_text="External profile picture URL (from OAuth providers)",
                max_length=500,
            ),
        ),
    ]
