# Generated by Django 5.2.11 on 2026-02-23 12:25

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_google_id_user_profile_picture_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True,
                help_text="International phone number (e.g., +1 234 567 8900)",
                max_length=20,
                validators=[core.validators.validate_phone_number],
            ),
        ),
    ]
