# Generated by Django 5.2.11 on 2026-02-25 17:07

import apps.users.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_user_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="mentorkyc",
            name="cv",
            field=models.FileField(
                blank=True,
                help_text="Curriculum Vitae (PDF/DOCX)",
                null=True,
                upload_to="kyc/cvs/mentors/%Y/%m/",
                validators=[apps.users.validators.validate_cv_file],
            ),
        ),
        migrations.AddField(
            model_name="mentorkyc",
            name="display_picture",
            field=models.ImageField(
                blank=True,
                help_text="Profile display picture (required)",
                null=True,
                upload_to="kyc/profile_pictures/%Y/%m/",
                validators=[apps.users.validators.validate_image_file],
            ),
        ),
        migrations.AddField(
            model_name="mentorkyc",
            name="employment_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("employed", "Employed"),
                    ("self_employed", "Self-Employed"),
                    ("student", "Student"),
                    ("unemployed", "Unemployed"),
                ],
                help_text="Employment status",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="mentorkyc",
            name="location",
            field=models.CharField(
                blank=True, help_text="City/Country location", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="mentorkyc",
            name="marital_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("single", "Single"),
                    ("married", "Married"),
                    ("divorced", "Divorced"),
                    ("widowed", "Widowed"),
                ],
                help_text="Marital status",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="mentorkyc",
            name="mentorship_types",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Types of mentorship offered (multi-select)",
            ),
        ),
        migrations.AddField(
            model_name="mentorkyc",
            name="national_id_number",
            field=models.CharField(
                blank=True,
                help_text="National ID number for KYC verification",
                max_length=50,
                validators=[apps.users.validators.validate_national_id],
            ),
        ),
        migrations.AddField(
            model_name="mentorkyc",
            name="profile_description",
            field=models.TextField(
                blank=True,
                help_text="Profile description / bio about mentor experience and expertise",
            ),
        ),
        migrations.AlterField(
            model_name="mentorkyc",
            name="government_id",
            field=models.FileField(
                blank=True,
                help_text="[LEGACY] Government-issued ID (passport, driver's license, national ID)",
                null=True,
                upload_to="kyc/government_ids/%Y/%m/",
            ),
        ),
        migrations.AlterField(
            model_name="mentorkyc",
            name="government_id_type",
            field=models.CharField(
                blank=True,
                help_text="[LEGACY] Type of government ID uploaded",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="MenteeKYC",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "display_picture",
                    models.ImageField(
                        blank=True,
                        help_text="Profile display picture (required)",
                        null=True,
                        upload_to="kyc/profile_pictures/%Y/%m/",
                        validators=[apps.users.validators.validate_image_file],
                    ),
                ),
                (
                    "national_id_number",
                    models.CharField(
                        blank=True,
                        help_text="National ID number for KYC verification",
                        max_length=50,
                        validators=[apps.users.validators.validate_national_id],
                    ),
                ),
                (
                    "marital_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("single", "Single"),
                            ("married", "Married"),
                            ("divorced", "Divorced"),
                            ("widowed", "Widowed"),
                        ],
                        help_text="Marital status",
                        max_length=20,
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, help_text="Country of residence", max_length=100
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, help_text="City of residence", max_length=100
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Additional address details (optional)",
                        max_length=200,
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        help_text="Phone number (Ghana format: +233 XX XXX XXXX)",
                        max_length=20,
                        validators=[apps.users.validators.validate_ghana_phone],
                    ),
                ),
                (
                    "employment_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("employed", "Employed"),
                            ("self_employed", "Self-Employed"),
                            ("student", "Student"),
                            ("unemployed", "Unemployed"),
                        ],
                        help_text="Current employment status",
                        max_length=30,
                    ),
                ),
                (
                    "linkedin_url",
                    models.URLField(
                        blank=True,
                        help_text="LinkedIn profile URL (optional)",
                        validators=[apps.users.validators.validate_linkedin_url],
                    ),
                ),
                (
                    "cv",
                    models.FileField(
                        blank=True,
                        help_text="Curriculum Vitae (optional, PDF/DOCX)",
                        null=True,
                        upload_to="kyc/cvs/mentees/%Y/%m/",
                        validators=[apps.users.validators.validate_cv_file],
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True,
                        help_text='Personal bio / profile statement ("Write something about yourself — surprise us")',
                    ),
                ),
                (
                    "mentorship_types",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Types of mentorship required (multi-select)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("under_review", "Under Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("requires_changes", "Requires Changes"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the application was submitted",
                        null=True,
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the application was reviewed",
                        null=True,
                    ),
                ),
                (
                    "review_notes",
                    models.TextField(
                        blank=True, help_text="Internal notes from the reviewer"
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True,
                        help_text="Reason for rejection (shown to applicant)",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin who reviewed the application",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_mentee_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mentee_kyc",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Mentee KYC",
                "verbose_name_plural": "Mentee KYC Applications",
                "db_table": "mentee_kyc",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="mentee_kyc_status_537840_idx"
                    ),
                    models.Index(
                        fields=["submitted_at"], name="mentee_kyc_submitt_696723_idx"
                    ),
                ],
            },
        ),
    ]
