# Generated by Django 5.2.11 on 2026-03-04 10:39

import apps.users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_add_suspension_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menteekyc",
            name="cv",
            field=models.FileField(
                blank=True,
                help_text="Curriculum Vitae (optional, PDF/DOCX)",
                null=True,
                upload_to="eaglesneaglets/documents/cvs/",
                validators=[apps.users.validators.validate_cv_file],
            ),
        ),
        migrations.AlterField(
            model_name="menteekyc",
            name="display_picture",
            field=models.ImageField(
                blank=True,
                help_text="Profile display picture (required)",
                null=True,
                upload_to="eaglesneaglets/images/profile_pictures/",
                validators=[apps.users.validators.validate_image_file],
            ),
        ),
        migrations.AlterField(
            model_name="mentorkyc",
            name="cv",
            field=models.FileField(
                blank=True,
                help_text="Curriculum Vitae (PDF/DOCX)",
                null=True,
                upload_to="eaglesneaglets/documents/cvs/",
                validators=[apps.users.validators.validate_cv_file],
            ),
        ),
        migrations.AlterField(
            model_name="mentorkyc",
            name="display_picture",
            field=models.ImageField(
                blank=True,
                help_text="Profile display picture (required)",
                null=True,
                upload_to="eaglesneaglets/images/profile_pictures/",
                validators=[apps.users.validators.validate_image_file],
            ),
        ),
        migrations.AlterField(
            model_name="mentorkyc",
            name="government_id",
            field=models.FileField(
                blank=True,
                help_text="[LEGACY] Government-issued ID (passport, driver's license, national ID)",
                null=True,
                upload_to="eaglesneaglets/documents/government_ids/",
            ),
        ),
        migrations.AlterField(
            model_name="mentorkyc",
            name="recommendation_letter",
            field=models.FileField(
                blank=True,
                help_text="Recommendation letter from pastor or ministry leader",
                null=True,
                upload_to="eaglesneaglets/documents/recommendations/",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="eaglesneaglets/images/profile_pictures/",
            ),
        ),
    ]
