# Generated by Django 5.2.11 on 2026-03-10 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_menteekyc_cv_alter_menteekyc_display_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='ip_address',
            field=models.GenericIPAddressField(db_index=True),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='session_key',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AddIndex(
            model_name='loginhistory',
            index=models.Index(fields=['user', 'success'], name='login_histo_user_id_e15ff5_idx'),
        ),
        migrations.AddIndex(
            model_name='loginhistory',
            index=models.Index(fields=['ip_address'], name='login_histo_ip_addr_3ce48d_idx'),
        ),
        migrations.AddIndex(
            model_name='loginhistory',
            index=models.Index(fields=['created_at'], name='login_histo_created_094722_idx'),
        ),
    ]
