# Generated by Django 5.2.11 on 2026-03-23 04:30

import apps.users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_change_country_default_to_ghana"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menteekyc",
            name="display_picture",
            field=models.ImageField(
                blank=True,
                help_text="Profile display picture (required)",
                max_length=500,
                null=True,
                upload_to="eaglesneaglets/images/profile_pictures/",
                validators=[apps.users.validators.validate_image_file],
            ),
        ),
        migrations.AlterField(
            model_name="mentorkyc",
            name="display_picture",
            field=models.ImageField(
                blank=True,
                help_text="Profile display picture (required)",
                max_length=500,
                null=True,
                upload_to="eaglesneaglets/images/profile_pictures/",
                validators=[apps.users.validators.validate_image_file],
            ),
        ),
    ]
