# Generated by Django 5.2.11 on 2026-03-23 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_increase_display_picture_max_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menteekyc",
            name="cv",
            field=models.URLField(
                blank=True,
                help_text="Cloudinary secure_url of the CV",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="menteekyc",
            name="display_picture",
            field=models.URLField(
                blank=True,
                help_text="Cloudinary secure_url of the profile picture",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="mentorkyc",
            name="cv",
            field=models.URLField(
                blank=True,
                help_text="Cloudinary secure_url of the CV",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="mentorkyc",
            name="display_picture",
            field=models.URLField(
                blank=True,
                help_text="Cloudinary secure_url of the profile picture",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="mentorkyc",
            name="recommendation_letter",
            field=models.URLField(
                blank=True,
                help_text="Cloudinary secure_url of the recommendation letter",
                max_length=500,
                null=True,
            ),
        ),
    ]
