# Generated by Django 5.2.11 on 2026-05-02 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_emailchangerequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_visibility",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("nest_only", "Nest Only"),
                    ("private", "Private"),
                ],
                default="public",
                max_length=10,
            ),
        ),
    ]
