# Generated by Django 5.2.11 on 2026-05-28 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0017_admin_invite_hash_tokens"),
    ]

    operations = [
        migrations.AddField(
            model_name="mentorkyc",
            name="code_of_conduct_text",
            field=models.TextField(
                blank=True,
                help_text="Immutable plain-text snapshot of the Mentor Code of Conduct as agreed at sign time",
            ),
        ),
        migrations.AddField(
            model_name="mentorkyc",
            name="code_of_conduct_version",
            field=models.CharField(
                blank=True,
                help_text="Version of the Mentor Code of Conduct the mentor agreed to",
                max_length=40,
            ),
        ),
    ]
