# Generated by Django 5.2.11 on 2026-05-29 02:36

import apps.users.validators
import core.fields
from django.db import migrations


def encrypt_existing_national_ids(apps, schema_editor):
    """Re-save existing rows so plaintext national IDs become encrypted at rest.

    Reading decrypts (or passes through legacy plaintext); saving re-encrypts via
    EncryptedCharField.get_prep_value. No-op when ENCRYPTION_KEY is unset.
    """
    for model_name in ("MenteeKYC", "MentorKYC"):
        Model = apps.get_model("users", model_name)
        for row in Model.objects.exclude(national_id_number="").iterator():
            row.save(update_fields=["national_id_number"])


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0018_mentorkyc_code_of_conduct_text_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menteekyc",
            name="national_id_number",
            field=core.fields.EncryptedCharField(
                blank=True,
                help_text="National ID number for KYC verification (encrypted at rest)",
                validators=[apps.users.validators.validate_national_id],
            ),
        ),
        migrations.AlterField(
            model_name="mentorkyc",
            name="national_id_number",
            field=core.fields.EncryptedCharField(
                blank=True,
                help_text="National ID number for KYC verification (encrypted at rest)",
                validators=[apps.users.validators.validate_national_id],
            ),
        ),
        migrations.RunPython(
            encrypt_existing_national_ids,
            migrations.RunPython.noop,
        ),
    ]
