# Generated by Django 5.2.11 on 2026-06-11 20:21
#
# Platform home is Accra, Ghana (GMT/UTC+0). 'Africa/Lagos' (UTC+1) was an
# incorrect scaffold default — flip both the default and the rows that still
# carry it (users never chose Lagos; it was applied silently).

from django.db import migrations, models

# Staging table records which profiles were Lagos→Accra in forward so reverse
# can revert only those rows (not users who legitimately chose Accra).
_STAGING_TABLE = "_users_0021_lagos_migrated"


def _create_staging_table(schema_editor):
    schema_editor.execute(
        f"CREATE TABLE {_STAGING_TABLE} (profile_id BIGINT PRIMARY KEY)"
    )


def _drop_staging_table(schema_editor):
    schema_editor.execute(f"DROP TABLE IF EXISTS {_STAGING_TABLE}")


def _load_staged_profile_ids(schema_editor):
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(f"SELECT profile_id FROM {_STAGING_TABLE}")
        return [row[0] for row in cursor.fetchall()]


def lagos_to_accra(apps, schema_editor):
    UserProfile = apps.get_model("users", "UserProfile")
    _create_staging_table(schema_editor)

    qs = UserProfile.objects.filter(timezone="Africa/Lagos")
    migrated_ids = list(qs.values_list("pk", flat=True))
    if migrated_ids:
        qs.update(timezone="Africa/Accra")
        with schema_editor.connection.cursor() as cursor:
            cursor.executemany(
                f"INSERT INTO {_STAGING_TABLE} (profile_id) VALUES (%s)",
                [(pk,) for pk in migrated_ids],
            )


def _staging_table_exists(schema_editor):
    with schema_editor.connection.cursor() as cursor:
        return _STAGING_TABLE in schema_editor.connection.introspection.table_names(
            cursor
        )


def accra_to_lagos(apps, schema_editor):
    """Reverse only rows this migration changed (Lagos scaffold default).

    Without the staging table, reverting every Africa/Accra row would corrupt
    users who legitimately set Accra or any other post-migrate Accra default.
    """
    if not _staging_table_exists(schema_editor):
        return

    UserProfile = apps.get_model("users", "UserProfile")
    migrated_ids = _load_staged_profile_ids(schema_editor)

    if migrated_ids:
        UserProfile.objects.filter(
            pk__in=migrated_ids,
            timezone="Africa/Accra",
        ).update(timezone="Africa/Lagos")

    _drop_staging_table(schema_editor)


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0020_mentorapplication_mentorapplicationaudit_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="timezone",
            field=models.CharField(default="Africa/Accra", max_length=50),
        ),
        migrations.RunPython(lagos_to_accra, accra_to_lagos),
    ]
