# Generated by Django 5.2.11 on 2026-03-04 09:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EngagementLog",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="E.g. 'login', 'content_view', 'post_created'.",
                        max_length=50,
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        blank=True,
                        help_text="Model name: 'nest', 'content_item', 'assignment'.",
                        max_length=30,
                    ),
                ),
                ("target_id", models.UUIDField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="engagement_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "engagement_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="engagement__user_id_7d2685_idx",
                    ),
                    models.Index(
                        fields=["action", "-created_at"],
                        name="engagement__action_c1e775_idx",
                    ),
                ],
            },
        ),
    ]
