"""apps.users.views package — split from monolithic views.py in Phase 11.5-04."""

from .auth import (
    RegisterView,
    CsrfTokenView,
    LoginView,
    LogoutView,
    CustomTokenRefreshView,
    EmailVerificationView,
    ResendVerificationView,
    PasswordResetRequestView,
    PasswordResetConfirmView,
    PasswordChangeView,
    CurrentUserView,
)
from .kyc import (
    MentorKYCView,
    MentorKYCStepView,
    MentorKYCSubmitView,
    UploadGovernmentIDView,
    UploadRecommendationView,
)
from .profile import (
    EagletProfileView,
    EagletOnboardingView,
    EagletSkipOnboardingView,
    MentorProfileView,
    MenteeProfileView,
    ProfileSubmitView,
    UploadDisplayPictureView,
    AvatarView,
    UploadCVView,
)
from .oauth import (
    GoogleOAuthLoginView,
    GoogleOAuthCallbackView,
)
from .admin import (
    AdminKYCListView,
    AdminKYCDetailView,
    AdminKYCStartReviewView,
    AdminKYCApproveView,
    AdminKYCRejectView,
    AdminKYCRequestChangesView,
    AdminKYCNotesView,
    AdminDashboardStatsView,
    AdminUserListView,
    AdminSuspendUserView,
    AdminReactivateUserView,
)
from .availability import (
    MentorAvailabilityView,
    MentorAvailabilityDetailView,
    PublicMentorAvailabilityView,
)
from .account import (
    EmailChangeRequestView,
    EmailChangeConfirmView,
    AccountDeleteView,
)
from .mentor_application import (
    MentorApplicationView,
    MentorApplicationWithdrawView,
    AdminMentorApplicationListView,
    AdminMentorApplicationDecisionView,
)

__all__ = [
    "RegisterView",
    "CsrfTokenView",
    "LoginView",
    "LogoutView",
    "CustomTokenRefreshView",
    "EmailVerificationView",
    "ResendVerificationView",
    "PasswordResetRequestView",
    "PasswordResetConfirmView",
    "PasswordChangeView",
    "CurrentUserView",
    "MentorKYCView",
    "MentorKYCStepView",
    "MentorKYCSubmitView",
    "UploadGovernmentIDView",
    "UploadRecommendationView",
    "EagletProfileView",
    "EagletOnboardingView",
    "EagletSkipOnboardingView",
    "MentorProfileView",
    "MenteeProfileView",
    "ProfileSubmitView",
    "UploadDisplayPictureView",
    "AvatarView",
    "UploadCVView",
    "GoogleOAuthLoginView",
    "GoogleOAuthCallbackView",
    "AdminKYCListView",
    "AdminKYCDetailView",
    "AdminKYCStartReviewView",
    "AdminKYCApproveView",
    "AdminKYCRejectView",
    "AdminKYCRequestChangesView",
    "AdminKYCNotesView",
    "AdminDashboardStatsView",
    "AdminUserListView",
    "AdminSuspendUserView",
    "AdminReactivateUserView",
    "MentorAvailabilityView",
    "MentorAvailabilityDetailView",
    "PublicMentorAvailabilityView",
    "EmailChangeRequestView",
    "EmailChangeConfirmView",
    "AccountDeleteView",
    "MentorApplicationView",
    "MentorApplicationWithdrawView",
    "AdminMentorApplicationListView",
    "AdminMentorApplicationDecisionView",
]
