# Generated by Django 5.2.11 on 2026-03-14 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('mentorship_request', 'Mentorship Request'), ('mentorship_approved', 'Mentorship Approved'), ('mentorship_rejected', 'Mentorship Rejected'), ('content_published', 'Content Published'), ('points_awarded', 'Points Awarded'), ('badge_earned', 'Badge Earned'), ('nest_post', 'Nest Post'), ('assignment_graded', 'Assignment Graded'), ('general', 'General'), ('post_like', 'Post Liked'), ('post_comment', 'Post Commented')], default='general', max_length=30),
        ),
    ]
