# Generated by Django 5.2.11 on 2026-05-02 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_add_mm18_notification_types"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("mentorship_request", "Mentorship Request"),
                            ("mentorship_approved", "Mentorship Approved"),
                            ("mentorship_rejected", "Mentorship Rejected"),
                            ("content_published", "Content Published"),
                            ("points_awarded", "Points Awarded"),
                            ("badge_earned", "Badge Earned"),
                            ("nest_post", "Nest Post"),
                            ("assignment_graded", "Assignment Graded"),
                            ("general", "General"),
                            ("post_like", "Post Liked"),
                            ("post_comment", "Post Commented"),
                            ("chat_message", "Chat Message"),
                            ("order_confirmed", "Order Confirmed"),
                            ("payment_received", "Payment Received"),
                        ],
                        max_length=30,
                    ),
                ),
                ("email_enabled", models.BooleanField(default=True)),
                ("inapp_enabled", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_prefs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "notification_preference",
                "indexes": [
                    models.Index(
                        fields=["user", "event_type"],
                        name="notificatio_user_id_6a6fa7_idx",
                    )
                ],
                "unique_together": {("user", "event_type")},
            },
        ),
    ]
